image: node:latest

before_script:
  - apt-get update
  - yarn config set cache-folder .yarn
  - yarn install

stages:
  - build
  - test
  - deploy

build_project:
  stage: build
  only:
    - master
  script:
    - npm run build --prod

test_with_lab:
  stage: test
  only:
    - master
  script:
    - apt-get -y install chromium
    - export CHROME_BIN=/usr/bin/chromium
    - npm run test

deploy_front:
  stage: deploy
  only:
    - master
  script:
    - apt-get -y install ansible python-pip rsync
    - pip install 'ansible==2.2.1.0'
    - cp -f ansible.cfg /etc/ansible
    - echo -e "$ANSIBLE_KEY_SSH_FRONT" > /etc/ansible/front_server
    - echo -e "$ANSIBLE_HOSTS" > /etc/ansible/hosts.yml
    - chmod 0600 /etc/ansible/front_server
    - npm run build --prod
    - ansible-playbook playbook.yml
